[package]
name = "goxoy-socket-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
goxoy-address-parser = "0.0.3"
goxoy-socket-client = "0.1.3"